<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="urn:healthmedia:wsdl:user:soap:v1" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:user-v1="urn:healthmedia:wsdl:user:v1"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsam="http://www.w3.org/2007/02/addressing/metadata"
	xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="urn:healthmedia:wsdl:user:soap:v1"
	name="userSoapService">
	
	<documentation>Version 1.0</documentation>
	
	<import location="./user-v1.wsdl" namespace="urn:healthmedia:wsdl:user:v1"/>
	
	<binding name="userSoapServiceBinding" type="user-v1:userService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="importUser">
			<soap:operation soapAction="urn:healthmedia:wsdl:user:soap:v1:importUser" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
			<fault name="error">
				<soap:fault use="literal" name="error"/>
			</fault>
		</operation>
	</binding>
	
	<!--  naming convention: this represents a factory class when generated. should be named according to its interface + function: UserServicePorts -->
	<service name="userSoapServicePorts">
		<wsp:Policy>
			<wsp:ExactlyOne>
				<wsp:All>
					<wsp:Policy>
						<sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</wsp:All>
			</wsp:ExactlyOne>
		</wsp:Policy>
		<!-- naming convention: represents a getter method on the factory class defined above. should be names after interface + function: UserServiceHttpPort -->
		<port binding="tns:userSoapServiceBinding" name="userSoapServicePort">
			<soap:address location="http://localhost:8080/user-service/userService" />
		</port>
	</service>
</definitions>
