<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="urn:healthmedia:policy:common-policy:v1"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsam="http://www.w3.org/2007/02/addressing/metadata"
	xmlns:i18np="http://www.w3.org/2008/04/ws-i18np"
	targetNamespace="urn:healthmedia:policy:common-policy:v1"
	name="commonPolicy">
	
	<documentation>Version 1.0</documentation>
	
	<wsp:Policy xml:id="i18nPolicy">
		<i18np:i18n />
	</wsp:Policy>

</definitions>