<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="urn:healthmedia:wsdl:user:http:v1" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:abs="urn:healthmedia:wsdl:user:v1"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="urn:healthmedia:wsdl:user:http:v1"
	name="UserServiceHttp">
	
	<documentation>Version 1.0</documentation>
	
	<import location="./user-v1.wsdl" namespace="urn:healthmedia:wsdl:user:v1"/>
	
	<!-- part of concrete wsdl. binds portType to a particular protocol. (e.g. soap over http)-->
	<binding name="UserServiceHttpBinding" type="abs:UserService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="AddUser">
			<soap:operation soapAction="urn:healthmedia:wsdl:user:http:v1/AddUser" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	
	<!-- part of concrete wsdl. defines ports/endpoints that expose a binding -->
	<!--  naming convention: this represents a factory class when generated. should be named according to its interface + function: UserServicePorts -->
	<service name="UserServicePorts">
		<!-- naming convention: represents a getter method on the factory class defined above. should be names after interface + function: UserServiceHttpPort -->
		<port binding="tns:UserServiceHttpBinding" name="UserServiceHttpPort">
			<soap:address location="http://www.example.org/" />
		</port>
	</service>
</definitions>
